export enum WeekActionType {
    
    WEEK_ADDED = 'WEEK_ADDED',
    WEEK_ERROR = 'WEEK_ERROR',
    SHOW_GOAL_FORM = 'SHOW_GOAL_FORM',
    HIDE_GOAL_FORM = 'HIDE_GOAL_FORM',
    SUBMIT_GOAL_FORM = 'SUBMIT_GOAL_FORM',
    NEW_GOAL_ADDED = 'NEW_GOAL_ADDED',
    GOAL_ADDED_TO_WEEK = 'GOAL_ADDED_TO_WEEK',
    GOAL_UPDATED_OF_WEEK = 'GOAL_UPDATED_OF_WEEK',
    GOAL_ERROR = 'GOAL_ERROR',
    WEEK_FETCHED = 'WEEK_FETCHED',
    NEW_TASK_ADDED = 'NEW_TASK_ADDED',
    SET_TASK_VIEW = 'SET_TASK_VIEW'

}