export enum ActionType {
    APP_STARTING = 'APP_STARTING',
    ACCOUNT_LOGGEDIN = 'ACCOUNT_LOGGEDIN',
    ACCOUNT_CREATED= 'ACCOUNT_CREATED',
    ACCOUNT_ERROR= 'ACCOUNT_ERROR',
    LOGIN_FAILED = 'LOGIN_FAILED',
    TOAST = 'TOAST',
    TOAST_ERROR = 'TOAST_ERROR',
    LOG_OUT = 'LOG_OUT',
    NEXT_ACTION = 'NEXT_ACTION',
    NEXT_ACTION_HIW = "how-it-works",
    NEXT_ACTION_DG = "default-goals",
    NEXT_ACTION_DWT= "default-week-template",
    NEXT_ACTION_DWS = "default-week-schedule",

    DEFAULT_GOALS_ADDED = "DEFAULT_GOALS_ADDED",
    DEFAULT_GOALS_FETCHED = "DEFAULT_GOALS_FETCHED",
    NEW_GOAL_ADDED = "NEW_GOAL_ADDED"

}