export enum ActionType {
    APP_STARTING = 'APP_STARTING',
    ACCOUNT_LOGGEDIN = 'ACCOUNT_LOGGEDIN',
    LOGIN_FAILED = 'LOGIN_FAILED',
    TOAST = 'TOAST',
    TOAST_ERROR = 'TOAST_ERROR',
    LOG_OUT = 'LOG_OUT',
}